wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    code_path: code/mmdetection/EfficientDet_train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1633482297
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.11
      5: 0.12.3
      8:
      - 5
batch_size:
  desc: null
  value: 4
epoch:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0001
name:
  desc: null
  value: efficientdet_d4
optimizer:
  desc: null
  value: AdamW
pretrained_model:
  desc: null
  value: efficientnet_b4
